spring:
  datasource:
    url: jdbc:tc:postgresql:15:///itmentor
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    com.example.it.mentor: DEBUG
    org.springframework.security: WARN
    liquibase: INFO
