logging:
  level:
    com.example.it.mentor: DEBUG
    org.springframework.security: DEBUG
    liquibase: INFO

# Раскомментировать при запуске MailHog (docker-compose up mailhog):
# spring:
#   mail:
#     host: localhost
#     port: 1025
#     properties:
#       mail.smtp.auth: false
#       mail.smtp.starttls.enable: false
#       mail.smtp.ssl.enable: false
