logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%-5level) %clr([%X{requestId:--}] [%X{userId:--}]){faint} %clr(%logger{36}){cyan} - %msg%n"
  level:
    com.example.it.mentor: DEBUG
    org.springframework.security: DEBUG
    liquibase: INFO

spring:
  mail:
    host: localhost
    port: 1025
    username: noreply@itmentor.local
    password: ''
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
      mail.smtp.ssl.enable: false
