--liquibase formatted sql

--changeset itmentor:031-seed-cities-extended labels:seed
INSERT INTO dict_city (name, region, country)
VALUES
-- Россия — крупные города
('Краснодар',        'Краснодарский край',          'Россия'),
('Ростов-на-Дону',   'Ростовская область',           'Россия'),
('Уфа',              'Республика Башкортостан',      'Россия'),
('Самара',           'Самарская область',             'Россия'),
('Воронеж',          'Воронежская область',           'Россия'),
('Красноярск',       'Красноярский край',             'Россия'),
('Пермь',            'Пермский край',                 'Россия'),
('Волгоград',        'Волгоградская область',         'Россия'),
('Тюмень',           'Тюменская область',             'Россия'),
('Иркутск',          'Иркутская область',             'Россия'),
('Хабаровск',        'Хабаровский край',              'Россия'),
('Владивосток',      'Приморский край',               'Россия'),
('Омск',             'Омская область',                'Россия'),
('Томск',            'Томская область',               'Россия'),
('Саратов',          'Саратовская область',           'Россия'),
('Ижевск',           'Удмуртская Республика',         'Россия'),
('Ульяновск',        'Ульяновская область',           'Россия'),
('Барнаул',          'Алтайский край',                'Россия'),
('Тольятти',         'Самарская область',             'Россия'),
('Кемерово',         'Кемеровская область',           'Россия'),
('Рязань',           'Рязанская область',             'Россия'),
('Набережные Челны', 'Республика Татарстан',          'Россия'),
('Астрахань',        'Астраханская область',          'Россия'),
('Пенза',            'Пензенская область',             'Россия'),
('Липецк',           'Липецкая область',              'Россия'),
('Тула',             'Тульская область',              'Россия'),
('Киров',            'Кировская область',             'Россия'),
('Чебоксары',        'Чувашская Республика',          'Россия'),
('Калининград',      'Калининградская область',       'Россия'),
('Сочи',             'Краснодарский край',            'Россия'),
('Мурманск',         'Мурманская область',            'Россия'),
('Архангельск',      'Архангельская область',         'Россия'),
('Ярославль',        'Ярославская область',           'Россия'),
('Оренбург',         'Оренбургская область',          'Россия'),
('Новокузнецк',      'Кемеровская область',           'Россия'),
('Белгород',         'Белгородская область',          'Россия'),
('Владимир',         'Владимирская область',          'Россия'),
('Чита',             'Забайкальский край',            'Россия'),
('Якутск',           'Республика Саха (Якутия)',      'Россия'),
-- СНГ
('Минск',            NULL,                            'Беларусь'),
('Алматы',           NULL,                            'Казахстан'),
('Астана',           NULL,                            'Казахстан'),
('Тбилиси',          NULL,                            'Грузия'),
('Ереван',           NULL,                            'Армения'),
('Ташкент',          NULL,                            'Узбекистан'),
('Бишкек',           NULL,                            'Кыргызстан'),
('Баку',             NULL,                            'Азербайджан'),
('Душанбе',          NULL,                            'Таджикистан'),
-- Европа — IT-хабы
('Берлин',           NULL,                            'Германия'),
('Мюнхен',           NULL,                            'Германия'),
('Гамбург',          NULL,                            'Германия'),
('Амстердам',        NULL,                            'Нидерланды'),
('Лондон',           NULL,                            'Великобритания'),
('Дублин',           NULL,                            'Ирландия'),
('Барселона',        NULL,                            'Испания'),
('Мадрид',           NULL,                            'Испания'),
('Варшава',          NULL,                            'Польша'),
('Вроцлав',          NULL,                            'Польша'),
('Краков',           NULL,                            'Польша'),
('Прага',            NULL,                            'Чехия'),
('Брно',             NULL,                            'Чехия'),
('Белград',          NULL,                            'Сербия'),
('Загреб',           NULL,                            'Хорватия'),
('Таллин',           NULL,                            'Эстония'),
('Рига',             NULL,                            'Латвия'),
('Вильнюс',          NULL,                            'Литва'),
('Лиссабон',         NULL,                            'Португалия'),
('Никосия',          NULL,                            'Кипр'),
('Лимасол',          NULL,                            'Кипр'),
('Цюрих',            NULL,                            'Швейцария'),
('Стамбул',          NULL,                            'Турция'),
('Анкара',           NULL,                            'Турция'),
-- Азия
('Дубай',            NULL,                            'ОАЭ'),
('Абу-Даби',         NULL,                            'ОАЭ'),
('Сингапур',         NULL,                            'Сингапур'),
('Бангалор',         NULL,                            'Индия'),
('Гиндерабад',       NULL,                            'Индия'),
-- Северная Америка
('Сан-Франциско',    'Калифорния',                    'США'),
('Нью-Йорк',         'Нью-Йорк',                      'США'),
('Сиэтл',            'Вашингтон',                     'США'),
('Остин',            'Техас',                         'США'),
('Торонто',          'Онтарио',                       'Канада'),
('Ванкувер',         'Британская Колумбия',           'Канада')
ON CONFLICT DO NOTHING;
--rollback SELECT 1;

--changeset itmentor:031-seed-skills-extended labels:seed
INSERT INTO dict_skill (name, category)
VALUES
-- AI / LLM / MLOps — самое горячее
('LLM (Large Language Models)', 'AI/ML'),
('Prompt Engineering',          'AI/ML'),
('RAG (Retrieval-Augmented Generation)', 'AI/ML'),
('LangChain',                   'AI/ML'),
('LlamaIndex',                  'AI/ML'),
('OpenAI API',                  'AI/ML'),
('Hugging Face Transformers',   'AI/ML'),
('Fine-tuning LLMs',            'AI/ML'),
('Vector Databases',            'AI/ML'),
('Embeddings',                  'AI/ML'),
('AI Agents',                   'AI/ML'),
('Computer Vision',             'AI/ML'),
('NLP',                         'AI/ML'),
('TensorFlow',                  'AI/ML'),
('PyTorch',                     'AI/ML'),
('scikit-learn',                'AI/ML'),
('MLflow',                      'AI/ML'),
('Weights & Biases',            'AI/ML'),
('ONNX',                        'AI/ML'),
('Triton Inference Server',     'AI/ML'),
-- Backend languages
('Go',                          'Backend'),
('Rust',                        'Backend'),
('C#',                          'Backend'),
('.NET / ASP.NET Core',         'Backend'),
('Node.js',                     'Backend'),
('PHP',                         'Backend'),
('Ruby',                        'Backend'),
('Scala',                       'Backend'),
('Kotlin',                      'Backend'),
('Elixir',                      'Backend'),
-- Backend frameworks
('FastAPI',                     'Backend'),
('Django',                      'Backend'),
('Flask',                       'Backend'),
('NestJS',                      'Backend'),
('Express.js',                  'Backend'),
('Gin',                         'Backend'),
('Fiber',                       'Backend'),
('Quarkus',                     'Backend'),
('Micronaut',                   'Backend'),
('Ktor',                        'Backend'),
('gRPC',                        'Backend'),
('GraphQL',                     'Backend'),
('REST API Design',             'Backend'),
('WebSockets',                  'Backend'),
-- Frontend frameworks & tools
('Vue.js',                      'Frontend'),
('Angular',                     'Frontend'),
('Next.js',                     'Frontend'),
('Nuxt.js',                     'Frontend'),
('Svelte / SvelteKit',          'Frontend'),
('Remix',                       'Frontend'),
('Astro',                       'Frontend'),
('Three.js / WebGL',            'Frontend'),
('Tailwind CSS',                'Frontend'),
('CSS-in-JS',                   'Frontend'),
('Vite',                        'Frontend'),
('Webpack',                     'Frontend'),
('Storybook',                   'Frontend'),
('Testing Library',             'Frontend'),
('Playwright',                  'Frontend'),
('Cypress',                     'Frontend'),
('WebAssembly',                 'Frontend'),
-- Mobile
('Flutter',                     'Mobile'),
('Swift / SwiftUI',             'Mobile'),
('Kotlin Multiplatform',        'Mobile'),
('React Native',                'Mobile'),
('Jetpack Compose',             'Mobile'),
-- Databases
('MongoDB',                     'Database'),
('Redis',                       'Database'),
('MySQL',                       'Database'),
('ClickHouse',                  'Database'),
('Cassandra',                   'Database'),
('Elasticsearch',               'Database'),
('Apache Kafka',                'Database'),
('RabbitMQ',                    'Database'),
('Pinecone',                    'Database'),
('Weaviate',                    'Database'),
('Qdrant',                      'Database'),
('TimescaleDB',                 'Database'),
('Neo4j',                       'Database'),
('DynamoDB',                    'Database'),
-- DevOps / Infrastructure / Cloud
('AWS',                         'DevOps'),
('Google Cloud Platform',       'DevOps'),
('Microsoft Azure',             'DevOps'),
('Yandex Cloud',                'DevOps'),
('Terraform',                   'DevOps'),
('Ansible',                     'DevOps'),
('Helm',                        'DevOps'),
('ArgoCD',                      'DevOps'),
('FluxCD',                      'DevOps'),
('GitHub Actions',              'DevOps'),
('GitLab CI/CD',                'DevOps'),
('Jenkins',                     'DevOps'),
('Prometheus',                  'DevOps'),
('Grafana',                     'DevOps'),
('OpenTelemetry',               'DevOps'),
('Jaeger / Zipkin',             'DevOps'),
('Nginx',                       'DevOps'),
('Istio / Service Mesh',        'DevOps'),
('Linux',                       'DevOps'),
('Bash / Shell Scripting',      'DevOps'),
-- Data Engineering
('Apache Spark',                'Data'),
('Apache Flink',                'Data'),
('Apache Airflow',              'Data'),
('dbt (Data Build Tool)',       'Data'),
('Pandas',                      'Data'),
('Polars',                      'Data'),
('Apache Iceberg',              'Data'),
('Delta Lake',                  'Data'),
('Databricks',                  'Data'),
('BigQuery',                    'Data'),
('Snowflake',                   'Data'),
-- Architecture & Design
('Microservices',               'Architecture'),
('Domain-Driven Design (DDD)',  'Architecture'),
('Event-Driven Architecture',   'Architecture'),
('CQRS / Event Sourcing',       'Architecture'),
('Clean Architecture',          'Architecture'),
('Hexagonal Architecture',      'Architecture'),
('System Design',               'Architecture'),
('API Gateway',                 'Architecture'),
-- Security
('OAuth 2.0 / OIDC',           'Security'),
('JWT / Sessions',              'Security'),
('Penetration Testing',         'Security'),
('OWASP Top 10',               'Security'),
('SAST / DAST',                'Security'),
('Secret Management (Vault)',   'Security'),
-- Quality & Tooling
('Unit Testing / TDD',         'Quality'),
('Integration Testing',         'Quality'),
('E2E Testing',                 'Quality'),
('SonarQube',                  'Quality'),
('JMeter / k6',                'Quality'),
-- Soft & product skills
('Agile / Scrum',              'Management'),
('Product Management',          'Management'),
('Technical Writing',           'Management'),
('Code Review',                 'Management'),
('Mentoring & Coaching',        'Management'),
('Interview Preparation',       'Management')
ON CONFLICT DO NOTHING;
--rollback SELECT 1;

--changeset itmentor:031-seed-languages-extended labels:seed
INSERT INTO dict_language (name, code)
VALUES
('Турецкий',     'tr'),
('Арабский',     'ar'),
('Португальский','pt'),
('Итальянский',  'it'),
('Польский',     'pl'),
('Нидерландский','nl'),
('Корейский',    'ko'),
('Японский',     'ja'),
('Хинди',        'hi'),
('Украинский',   'uk'),
('Белорусский',  'be'),
('Казахский',    'kk'),
('Грузинский',   'ka'),
('Армянский',    'hy'),
('Шведский',     'sv'),
('Финский',      'fi'),
('Норвежский',   'no'),
('Датский',      'da'),
('Чешский',      'cs'),
('Венгерский',   'hu'),
('Румынский',    'ro'),
('Греческий',    'el'),
('Сербский',     'sr'),
('Хорватский',   'hr'),
('Вьетнамский',  'vi'),
('Индонезийский','id'),
('Тайский',      'th'),
('Узбекский',    'uz')
ON CONFLICT DO NOTHING;
--rollback SELECT 1;

--changeset itmentor:031-seed-interaction-types-extended labels:seed
INSERT INTO dict_interaction_type (name, description)
VALUES
('Менторинг по AI/ML',            'Погружение в машинное обучение и работу с языковыми моделями'),
('Архитектурный разбор',          'Совместный анализ и проектирование архитектуры системы'),
('Разбор пет-проекта',            'Обзор и улучшение личного проекта студента'),
('Mock-собеседование',            'Симуляция реального технического собеседования с фидбэком'),
('DevOps / Cloud практики',       'Настройка CI/CD, контейнеризация, облачный деплой'),
('Помощь с Open Source',          'Контрибьюция в open source: первые PR, ревью, roadmap'),
('Системное проектирование',      'Решение задач system design: высокая нагрузка, масштабирование'),
('Карьерная стратегия',           'Составление плана развития, выбор направления и уровня'),
('Помощь с резюме',               'Обзор резюме, LinkedIn, портфолио и сопроводительного письма'),
('Data Engineering менторинг',    'Пайплайны данных, ETL/ELT, хранилища данных'),
('Безопасность приложений',       'Разбор уязвимостей, OWASP, написание защищённого кода'),
('Продуктовые навыки',            'Задачи на стыке разработки и продукта: метрики, аналитика'),
('Soft skills для разработчика',  'Коммуникация, презентации, работа в команде, управление временем'),
('Frontend / UI-ревью',           'Обзор кода, производительности и UX фронтенд-решений'),
('Мобильная разработка',          'Обзор и менторинг по iOS, Android, Flutter или кроссплатформ')
ON CONFLICT DO NOTHING;
--rollback SELECT 1;
